display_name = "msgvault"

review_guidelines = """
We are using the latest production version of Go
Please be pragmatic about reviews, raising theoretical or highly
pedantic concerns will result in unnecessary code churn and wasted
review-fix cycles.
"""